name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update PYTHONPATH variable
      run: |
        echo "PYTHONPATH=trailstone" >> $GITHUB_ENV
    - name: Run tests
      working-directory: etl
      run: |
        pytest
